eliasdoehne/stellaris-dashboard

- src/stellarisdashboard/cython_ext/token_value_stream.pyx
This should fix #3 for the Cython code.
> Recognize escaped quotation marks (cython only)

- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/__init__.py
- stellarisdashboard/dashboard_app/graph_ledger.py
Add the ability to specify the bind IP. Use case: not running on localhost, e.g. on a different computer (I am currently playing on Windows and running stellaris-dashboard on Linux) or in Docker (where hard-binding to 127.0.0.1 won't ever work without adding a reverse proxy as well)
> Add ability to configure bind IP

- stellarisdashboard/dashboard_app/graph_ledger.py
- stellarisdashboard/dashboard_app/timelapse_exporter.py
Adds WebP animated export support. In my test of a tiny galaxy in 2350, the webp was 22% of the size of the gif:
```
-rw-rw-r-- 1 c c 16159972 Nov 21 19:48 mpseriousempirename_1645140075-2022-11-21-194604.gif
-rw-rw-r-- 1 c c  3572372 Nov 21 19:51 mpseriousempirename_1645140075-2022-11-21-194604.webp
```
The webp looks like this: https://freeimage.host/i/HJQpqwN
WebP is a "new" image format, where animated WebPs are [already well supported](https://developers.google.com/speed/webp/faq#which_web_browsers_natively_support_webp) by the browsers ("only" since 2020 for Edge); and since 2016 for libwebp and 2017 for Pillow, although I put a feature check on the checkbox, just in case.
The export is slower than gif. The [tuning options](https://pillow.readthedocs.io/en/stable/handbook/image-file- …
> Add ability to export as animated webp

- stellarisdashboard/parsing/timeline.py
This fix prevents the crash in #74. 
The line was commented out in #65, but as reported, this lets a None continue on until the crash on (currently) line 3038: https://github.com/eliasdoehne/stellaris-dashboard/blob/7542674b4374050aa058241ad69d4aa50c5af773/stellarisdashboard/parsing/timeline.py#L3038
Now only the (already existing) warning is emitted, and parsing continues.
```
MainProcess - 2022-11-23 13:32:48,590 - stellarisdashboard.parsing.timeline - WARNING - test_9673941 2256.04.06     Could not find country matching war participant {'call_type': 'primary', 'country': 12, 'caller': 4294967295, 'fleets_gone_mia': 0}
```
> Skip parsing a war when a participant country is unknown. Fixes #74

- stellarisdashboard/config.py
I noticed that setting `log_level: DEBUG` didn't make any `logger.debug()` messages appear on stdout.  This applies the setting from `config.yml` after the config file is read. and also enables more levels to be used
> Fix applying the wanted log level, and allow more levels

- requirements.txt
- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/graph_ledger.py
Dash prints a red Flask warning every startup:
```
MainProcess - 2022-12-05 15:11:56,080 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
```
This PR adds a new flag `production` that uses waitress instead of Dash to serve the WSGI app. (I picked waitress because out of the [Flask suggestions](https://flask.palletsprojects.com/en/2.2.x/deploying/) it was the first one I got working and it was a small change).
In my testing, nothing looked broken, and waitress is faster, mostly noticeable on first load (or with browser cache disabled)
Waitress:
Flask:
> Add option for production WSGI server

- stellarisdashboard/parsing/cython_ext/tokenizer.pyx
I've been running the dashboard on Python 3.10 / Cython==0.29.32. The following error happens then, and also with Python 3.8 (same Cython version -- not sure when the FutureWarning was introduced).  Whenever tokenizer.pyx gets compiled (manually: `python setup.py build_ext --inplace`), this warning is printed in red:
```
/home/stellaris/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/stellaris/stellaris-dashboard/stellarisdashboard/parsing/cython_ext/tokenizer.pyx
tree = Parsing.p_module(s, pxd, full_module_name)
```
Adding the language level to the top of the file silences it. And since Python 3 is required for this project, it seems like a …
> Add Cython language level to tokenizer.pyx

- stellarisdashboard/game_info.py
- stellarisdashboard/parsing/timeline.py
- test/names_test.py
The `%ADJECTIVE%` template is easy enough to add, but `%ADJ%` doesn't work the same way (see #90 for an example). In this solution I special-cased `%ADJ%` by (1) changing `%ADJ%` to `$1$` **and** (2) appending to the template (key) a few levels down to allow the recursive template replacement to properly replace and keep all parts of the name.
Also adds test cases.
> Handle new 3.6 templates: %ADJECTIVE%, %ADJ%, and %LEADER_2%. Fixes #90

- stellarisdashboard/dashboard_app/timelapse_exporter.py
I find the current text color (almost the same as the empire fill color) to be hard to read.  This takes a small part of #80 that isn't related to empire colors. It changes the empire name text on the timelapse export to a medium-size white with black outline. I found that the most readable, although I'm slightly sad to not be using the empire color in the text.
Image: https://i.imgur.com/1JIGcej.gif (wait til 2246)
Here is a comparison of several options considered: https://imgur.com/a/shYAEMS
> Change empire name in exported timelapse to medium white on black for readability

- stellarisdashboard/game_info.py
- test/localization_test_files/english/empire_formats_l_english.yml
- test/names_test.py
This fixes several missing localisation key:value pairs.
Before:
After:
The code previously assumed that the number after the colon would always be `0`, but it turns out that isn't true, and that we shouldn't care about it [1][2].  This PR picks up everything in the localisation files.
Example from `localisation/english/distant_stars_l_english.yml` (3.6.1):
```
NAME_Ketling_Multitude:1 "Ketling Star Pack"
```
Also adds a test for it.
Unfortunately I don't have a real save from when this happened in my game, but, I did fake one by replacing `"NAME_Ketling"` with `"NAME_Ketling_Multitude"` in a save file and it worked.
[1] https://stellaris.paradoxwikis.com/Localisation_modding#Localisation_Keys
[2] https://twitter.com/Martin_Anward/status/1039175213773144066
> Read more keys from localisation files

- README.md
- stellarisdashboard/parsing/rust_parser/src/parser.rs
- stellarisdashboard/parsing/timeline.py
Fixes https://github.com/eliasdoehne/stellaris-dashboard/issues/112
> Fix errors extracting data from 3.9 gamestate

- README.md
- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/settings.py
> Automatically find modded loc files, using dlc_load.json

- stellarisdashboard/dashboard_app/graph_ledger.py
- stellarisdashboard/dashboard_app/timelapse_exporter.py
- stellarisdashboard/dashboard_app/visualization_data.py
- stellarisdashboard/datamodel.py
- stellarisdashboard/parsing/rust_parser/src/parser.rs
- stellarisdashboard/parsing/timeline.py
Closes #80
A few notes:
- This tries to avoid duplicates by darkening/lighting colors (shifting the v in hsv)
- The actual resolved color of a country can change depending on what other countries exist in the DB, so game_id needs to passed in to `get_color_vals`
- Country colors for a given game_id are cached. If any countries are created, the cache is cleared
- This tries to avoid grayscale colors by using the secondary color if the primary color has low saturation
- A minimum v is enforced for readability
- I needed to enhance the rust parser to understand the color value syntax (eg `rgb { 1 2 3 }`, `hsv { 0.1 0.2 0.3 }`)
> Use country colors for graphs and maps; avoid duplicates

- stellarisdashboard/parsing/timeline.py
- test/parser_test.py
1. Old saves that don't have council_positions were failing to parse.  Add an existence check for the data structure in _update_council_positions().
2. The test for a full save parse did not propagate an exception back to the tester, causing false negatives (it only successfully tested the existence of the rust save parser). By setting config.CONFIG.debug_mode to True we hit code that propagates the exception, and the test properly fails when a save fails to parse.
Repro: `python -m pytest test/parser_test.py -k "test_real_save" -s`
1. On v6, prints a stack trace but does NOT fail the test
2. On this branch, does not print a stack strace and does not fail the test.
3. On this branch, if you remove the check-and-early-return for missing council_positions, the parse prints a trace and the …
> Fix save parser test, and fix error in parsing old saves

- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/visualization_data.py
- stellarisdashboard/game_info.py
I received the following warnings on Python 3.10.12.  (Python 3.12 changes them to SyntaxWarning).  This PR changes multiple strings fed to `re` in to raw strings (and yes, [f and r can be combined like that](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals)).
```
stellarisdashboard/config.py:459
/home/.../stellaris-dashboard/stellarisdashboard/config.py:459: DeprecationWarning: invalid escape sequence '\s'
match = re.match('^\s*path\s*=\s*"(.*)"\s*$', line)
stellarisdashboard/config.py:471
stellarisdashboard/config.py:471
/home/.../stellaris-dashboard/stellarisdashboard/config.py:471: DeprecationWarning: invalid escape sequence '\s'
match = re.match(f"^\ufeff\s*{language}\s*:\s*$", first_line)
test/parser_test.py::test_real_save …
```
> Fix warnings about invalid escape sequences

- requirements.txt
- stellarisdashboard/datamodel.py
> Use alembic to automatically migrate game DBs

- README.md
- mod/stellaris_dashboard/descriptor.mod
- stellarisdashboard/config.py
- stellarisdashboard/parsing/timeline.py
A few small commits rolled into one PR:
- perf improvement for timeline.py
- fix a crash processing policies in timeline.py
- better handling of OneDrive in Windows
- Updates for readme and mod descriptor
> Misc tweaks

- README.md
- mod/stellaris_dashboard/descriptor.mod
- stellarisdashboard/cli.py
- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/assets/style.css
- stellarisdashboard/dashboard_app/graph_ledger.py
- stellarisdashboard/dashboard_app/history_ledger.py
- stellarisdashboard/dashboard_app/settings.py
- stellarisdashboard/dashboard_app/templates/settings_page.html
- stellarisdashboard/dashboard_app/visualization_data.py
- stellarisdashboard/datamodel.py
- stellarisdashboard/parsing/timeline.py
Also:
- Improve settings UI
- Distinguish between Observer Mode and Player Not Found
- Fix bug with TimelineExtractor remembering state across saves
> Add "Hide other players setting"

- mod/stellaris_dashboard/descriptor.mod
- stellarisdashboard/dashboard_app/templates/history_page.html
- stellarisdashboard/parsing/rust_parser/src/parser.rs
- stellarisdashboard/parsing/timeline.py
This fixes 3 issues:
- memory leak caused by _get_or_add_shared_description #163
- parsing failure caused by initial "nan" being interpretted as `Not a Number` #164
- 500 error serving the event ledger, caused by missing leader (reported in Stellaris Modding Den discord)
Also bumps up the Stellaris version number in the mod descriptor (already updated on workshop)
> Parser and processor fixes

- stellarisdashboard/config.py
- stellarisdashboard/dashboard_app/assets/style.css
- stellarisdashboard/dashboard_app/game_index.py
- stellarisdashboard/dashboard_app/templates/game_index.html
Also fallback to system-ui font if verdana not available
Implements #165 
Screenshots:
> Add notifications to the main screen for no games and invalid settings

- stellarisdashboard/parsing/rust_parser/src/parser.rs
Not much to say besides the title. We simply needed to add `\` to the potentially escaped characters.
> Fix escaped backslash at end of quoted string erroneously escapes the final quote

- stellarisdashboard/dashboard_app/history_ledger.py
- stellarisdashboard/dashboard_app/templates/history_page.html
- stellarisdashboard/parsing/timeline.py
Planets were having their names and classes set to null
If there had previously been destruction or terraforming historical event, this could cause 500s in the event ledger
> Handle completely destroyed (removed from gamestate) planets

- stellarisdashboard/dashboard_app/graph_ledger.py
- stellarisdashboard/dashboard_app/visualization_data.py
The "Click the map to select a system" text was being almost immediately hidden upon loading the page, due to early return of `""` in the callback
While fixing that, I made an enhancement to split the link for the selected system into separate links for the system and country ledger pages, instead of just one for the system
> Fix select system instructional text not displayed, and split selected system ledger link into system and country

- mod/stellaris_dashboard/descriptor.mod
- mod/stellaris_dashboard/interface/main_bottom.gui
- stellarisdashboard/dashboard_app/utils.py
- stellarisdashboard/parsing/timeline.py
Rarely, leaders do not have countries
The leader died event wasn't accounting for that when getting the country_data
> Fix countryless leader died event

- mod/stellaris_dashboard/descriptor.mod
- mod/stellaris_dashboard/interface/main_bottom.gui
- stellarisdashboard/dashboard_app/utils.py
- stellarisdashboard/game_info.py
- test/localization_test_files/english/tagged_localization_test_strings.yml
- test/names_test.py
- Adds support for localization tags and variants (eg `message that adds tags&!tag1,tag2` and `default message|||requiredtag1,requiredtag2:variant message`)
- Adds support for roman numeral formatting
> Roman namelist fixes

- stellarisdashboard/parsing/rust_parser/src/parser.rs
- stellarisdashboard/parsing/save_parser.py
- test/parser_test_cases.py
Gamestate keys sometimes do not have values, eg `key1= key2=value`
We had some handling for this already, but instead of interpreting the above as
```js
{ key1: null, key2: "value" }
```
we interpreted it as
```js
{ key1: "value" }
```
Besides being incorrect, this also failed completely if a valueless key was the last in an object, eg `key1=value key2=`, as is the case in the saved attached to #187
> Fix save parse fails on valueless key

- stellarisdashboard/dashboard_app/graph_ledger.py
- Added check for `dpi` parameter to handle case where it was set to `None`
Details copied from #98:
It appears that the dpi parameter for `graph_ledger:trigger_timeline_export(...)` was not being checked for `None` in the case where the user did not interact with the html input control for DPI.
> Fix timelapse frame export (#98)
